"""
Tests for PR and deployment classification (agent / human / hybrid).
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from lucille.cfr.sources.github_client import GitHubPR
from lucille.cfr.logic.pr_classifier import is_agent_pr, classify_deployment

SAMPLE_CONFIG = {
    "cfr": {
        "agent_github_label": "agent-generated",
        "agent_author_patterns": ["claude-agent", "jaris-bot"],
        "failure_issue_types": ["Bug", "Incident"],
        "failure_labels": ["hotfix", "rollback"],
        "failure_title_patterns": ["hotfix", "rollback", "revert"],
    }
}


def _pr(author="alice", labels=None, body="", title="feat: add thing") -> GitHubPR:
    return GitHubPR(
        number=1,
        title=title,
        body=body,
        author=author,
        labels=labels or [],
        merged_at=datetime(2026, 2, 1, tzinfo=timezone.utc),
        base_branch="main",
        html_url="https://github.com/jarisdev/analytics/pull/1",
        repo="analytics",
    )


class TestIsAgentPR:
    def test_agent_label_detected(self):
        pr = _pr(labels=["agent-generated"])
        assert is_agent_pr(pr, SAMPLE_CONFIG) is True

    def test_agent_author_pattern_detected(self):
        pr = _pr(author="claude-agent[bot]")
        assert is_agent_pr(pr, SAMPLE_CONFIG) is True

    def test_jaris_bot_author_pattern_detected(self):
        pr = _pr(author="jaris-bot")
        assert is_agent_pr(pr, SAMPLE_CONFIG) is True

    def test_agent_marker_in_body(self):
        pr = _pr(body="[AGENT] auto-generated by workflow")
        assert is_agent_pr(pr, SAMPLE_CONFIG) is True

    def test_human_pr_not_flagged(self):
        pr = _pr(author="alice", labels=["feature"], body="Normal PR")
        assert is_agent_pr(pr, SAMPLE_CONFIG) is False

    def test_case_insensitive_author_match(self):
        pr = _pr(author="Claude-Agent")
        assert is_agent_pr(pr, SAMPLE_CONFIG) is True


class TestClassifyDeployment:
    def test_all_agent_prs_gives_agent_category(self):
        prs = [
            _pr(labels=["agent-generated"]),
            _pr(author="claude-agent"),
        ]
        assert classify_deployment(prs, SAMPLE_CONFIG) == "agent"

    def test_all_human_prs_gives_human_category(self):
        prs = [_pr(author="alice"), _pr(author="bob")]
        assert classify_deployment(prs, SAMPLE_CONFIG) == "human"

    def test_mixed_prs_gives_hybrid_category(self):
        prs = [
            _pr(author="alice"),
            _pr(labels=["agent-generated"]),
        ]
        assert classify_deployment(prs, SAMPLE_CONFIG) == "hybrid"

    def test_empty_pr_list_gives_human_category(self):
        assert classify_deployment([], SAMPLE_CONFIG) == "human"
